
abstract=
ontologyTitle=
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=https://w3id.org/utoronto/ontologies/SeisFront
ontologyName=Seismic Fragility Ontology
thisVersionURI=null
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=
licenseURI=null
licenseName=null
licenseIconURL=null
citeAs=Joaquín Acosta Reveco (j.acosta@mail.utoronto.ca).
DOI=
status=Ontology Specification Draft
logo=
description=
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Joaquín Acosta Reveco (j.acosta@mail.utoronto.ca)
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
